### ISSUE TITLE
Support doctrine/annotations v2

### ISSUE THREAD

**Issue by migo315** [playox/flagception-bundle#2]
Support new versions of https://packagist.org/packages/doctrine/annotations

Origin: https://github.com/bestit/flagception-bundle/issues/102

**Comment by yakobe** [comment]
Hi @migo315 , Any chance we could get this in? There's a [PR to the old repo](https://github.com/bestit/flagception-bundle/pull/105), maybe it's a quick win? 

There are quite a few things in this repo that are blocking other dependency upgrades. It would be great if we could get them up to date, even if it forces some major updates.

**Comment by teiling88** [comment]
Hey @yakobe,
feel free to create an own pr oder I will have a look into it later.
Greetings,
Thomas

**Comment by teiling88** [comment]
@yakobe have a look: https://github.com/playox/flagception-bundle/pull/14

**Comment by yakobe** [comment]
Thank you! 

Sorry, if i was stressing. I was just wondering if any of the existing pull requests from the old library could be used for quick wins. In future I will try to see if i can work out how to get a pull request in.

**Comment by teiling88** [comment]
Everything fine - I have to fix the pipeline and then we can merge and release it :-)

**Comment by teiling88** [comment]
Done - I will publish a new release the next minutes :-)
